import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-slate-100'>
      <body className={inter.className}>

        <div className="w-full md:flex justify-between md:px-10 px-4 md:my-10 my-4">
          <nav>
            <Link href="/">Home</Link>
          </nav>
          <div className="md:my-3">  
          <Link 
            className="tracking-wide font-light" 
            href="https://www.frontendmentor.io/profile/rajjubajra"
            target="_blank">
              Frontend Mentor Challages
            </Link>
          </div>
        </div>

        <div>
          {children}
        </div>
        
      </body>
    </html>
  )
}
